apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rahuldep111
  name: rahuldep111    # name of deployment 
  namespace: rahulns   # namespace info 
spec:
  replicas: 1   # no of pod 
  selector:
    matchLabels:
      app: rahuldep111
  strategy: {}
  template:   #  will be created by using template 
    metadata:
      creationTimestamp: null
      labels:   # label of my pod 
        app: rahuldep111
    spec:
      imagePullSecrets: # image pull secret 
      - name: rahulsec  # name of secret 
      containers:
      - image: oracleindia.azurecr.io/nginx:28thmay2021v1  # image from ACR 
        name: nginx # name of container 
#        command: ["/bin/sh","-c","ping fb.com"] # like in docker we give pp / same in k8s
        resources: {}
#      dnsPolicy: ClusterFirst
#      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rahulsvc1
  name: rahulsvc1 # name of service 
  namespace: rahulns # namespace info 
spec:
  ports:
  - name: 1294-80
    port: 1294 # service port 
    protocol: TCP
    targetPort: 80 # pod app port 
  selector: # Pod finder using below given labels 
   app: rahuldep111 # exactly same label as POD have 
  type: LoadBalancer # loadbalancer type of service 
  sessionAffinity: ClientIP
status:
  loadBalancer: {}

