apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod 
    run: rahulpod111 # key: value 
  name: rahulpod111 # name of pod 
  namespace: rahulns # namespace iNFO 
spec:
  imagePullSecrets:
  - name: rahulsec
  containers:
  - image: oracleindia.azurecr.io/nginx:28thmay2021v1 # DOcker img in ACR 
    name: rahulpod111 # name of container 
    ports:
    - containerPort: 80 # pod port 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
