apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 namespace: rahul-friend
 name: deploy-app-binding

subjects:
 - kind: ServiceAccount
   name: rahul
   apiGroup: ""
roleRef:
 kind: Role
 name: rahul-reader
 apiGroup: ""

