apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod
    run: ashuemppod
  name: ashuemppod # name of POD 
  namespace: ashuspace # namespace info 
spec:
  volumes: # creating volume 
  - name: ashuvol1 # volume name 
    emptyDir: {}   # it will create a random dir in scheduled minion node 
  - name: ashuvol2  # second volume 
    hostPath: # you can choose to create vol from specific source 
     path: /etc
     type: Directory 
  containers:
  - image: nginx
    name: ashuc1 
    volumeMounts:
    - name: ashuvol1 # name of volume 
      mountPath: /usr/share/nginx/html/
      readOnly: True
    - name: ashuvol2 # volume second 
      mountPath: /minionetc
      readOnly: True 
  - image: alpine
    name: ashuemppod
    volumeMounts: # mounting above created POD inside container
    - name: ashuvol1 # name of volume 
      mountPath: /mnt/oracle/ # this directory will be created automatically
    command: ["/bin/sh","-c","while true;do date >>/mnt/oracle/time.txt;sleep 5;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}