server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/rahulkumarsahu/config-server-properties
          uri: ${CONFIG_REPOSITORY}
          clone-on-start: true

# this is to connect with eureka server
#podname-{replica-index}.{serviceName}.default.svc.cluster.local -> to connect to service registry
eureka:
  instance:
    preferIpAddress: true
    hostname: ${CLIENT_HOSTNAME}
    #hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${CLIENT_EUREKA_SERVER_ADDRESS}
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka