apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-config
  name: service-config
  namespace: rahul
data:
  host: mysql-service
  db_name: microservice
  #eureka_service_address: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka,http://eureka-2.eureka:8761/eureka
  eureka_service_address: http://eureka-0.eureka:8761/eureka
  config_repository: https://github.com/rahulkumarsahu/config-server-properties
#  client_host_name: eureka-0
  gateway_host_name: gateway-service
  user_host_name: user-service
  department_host_name: department-service
  config_host_name: config-service
  hystrix_host_name: hystrix-service
  client_eureka_server_address: http://eureka-0.eureka.rahul.svc.cluster.local:8761/eureka
  #client_eureka_server_address: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:8761/eureka
  # if you want to deploy n instances of eureka cluster,
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka

  #data:
  #  config.json: |
  #    {
  #      "environment" : "dev"
  #    }
  # kubectl create configmap example-config --from-file ./golang/configs/config.json
