apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-config
  name: service-config
  namespace: rahul
data:
 eureka_service_address: http://eureka-0.eureka:8761/eureka
#To read from values.yaml
#  config.json: |-
#{
#    {{- range $key, $val := .Values.json }}
#    {{ $key | quote | indent 6}}: {{ $val | quote }}
#    {{- end}}
#}

#To read from json file
#{{ .Files.Get "config.json" | indent 4}}