server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/


# this is to connect with eureka server
#podname-{replica-index}.{serviceName}.default.svc.cluster.local -> to connect to service registry
eureka:
  instance:
    preferIpAddress: true
    hostname: ${CLIENT_HOSTNAME}
    #hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${CLIENT_EUREKA_SERVER_ADDRESS}
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka