server:
  port: 8761

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}


