# Create deployment for gateway application

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway-service
  name: gateway-service # name of deployment
  namespace: rahul # namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy: {}
  template: # template for pod creation
    metadata:
      creationTimestamp: null
      labels: # label of POD
        app: gateway-service
    spec:
      containers:
        - image: rahulkumar07/gateway:v1 # docker image from Docker hub
          name: gateway-service # container name
          imagePullPolicy: Always
          ports:
            - containerPort: 9191 # app  port
          env:
            - name: CLIENT_HOSTNAME
              valueFrom:
                configMapKeyRef:
                    name: service-config
                    key: gateway_host_name
            - name: CLIENT_EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                    name: service-config
                    key: client_eureka_server_address
          resources: {}
status: {}
---
# creating service for app pod  either Node port / LB type

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: rahul
spec:
  ports:
    - name: 9191-80
      port: 9191
  #    protocol: TCP
      targetPort: 80
  selector: # pod finder
    app: gateway-service # label of POD
  type: LoadBalancer
status:
  loadBalancer: {}