# persistent volume claim create some storage in cluster to store data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: service-pvc
  name: service-pvc # name of Deployment
  namespace: rahul # namespace
spec:
  accessModes:
    - ReadWriteOnce # This specifies the mode of the claim we are trying to create
  resources:
    requests:
      storage: 1Gi # this will tell amount of the claim we are trying to claim