# persistent volume which is storage which will get bind with persistent volume claim
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: service-pv
  name: service-pv
  namespace: rahul
spec:
  capacity:
    storage: 1Gi # this will tell amount of the claim we are trying to claim
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # This specifies the mode of the claim we are trying to create
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: D:\learning\docker\storage # path where we want to store data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1