# service registry :- stateful sets :- is particularly used for stateful service like db and registry where you have to maintain host.
#whenever we are creating deployment we will have dynamic pod name so we want host name unique which stateful sets (registry) can use for communication
#and it require headless service
#headless service will not have cluster ip and it will create endpoints internally to expose the pod to the kubernetes cluster
#when we are creating headless service and stateful sets then we can access by using this particular format

# creating headless service for stateful sets eureka

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eureka
  name: eureka
  namespace: rahul
spec:
  clusterIP: None # headless service
  ports:
    - name: 8761-80
      port: 8761
#      protocol: TCP
      targetPort: 80
  selector: # pod finder
    app: eureka # label of POD
status:
  loadBalancer: {}

---
# Create deployment for application

apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: eureka
  name: eureka # name of deployment
  namespace: rahul # namespace
spec:
  serviceName: 'eureka'
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template: # template for pod creation
    metadata:
      creationTimestamp: null
      labels: # label of POD
        app: eureka
    spec:
      containers:
        - image: rahulkumar07/registry:v1 # docker image from Docker hub
          name: eureka # container name
          imagePullPolicy: Always
          ports:
            - containerPort: 8761 # app  port
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1200Mi"
              cpu: "500m"
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: eureka_service_address

---
# creating service to connect stateful sets

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eureka
  name: eureka-lb
  namespace: rahul
spec:
  ports:
    - name: 8761-80
      port: 8761
#      protocol: TCP
      targetPort: 80
  selector: # pod finder
    app: eureka # label of POD
  type: LoadBalancer
status:
  loadBalancer: {}